### ISSUE TITLE
Error importing

### ISSUE THREAD

**Issue by para-dise** [jreese/aiosqlite#24]
### Description
`>>> import aiosqlite
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/home/user/.local/lib/python3.5/site-packages/aiosqlite-0.8.1-py3.5.egg/aiosqlite/__init__.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/home/user/.local/lib/python3.5/site-packages/aiosqlite-0.8.1-py3.5.egg/aiosqlite/core.py", line 110, in <module>
  File "/home/user/.local/lib/python3.5/site-packages/aiosqlite-0.8.1-py3.5.egg/aiosqlite/core.py", line 258, in Connection
  File "/usr/lib/python3.5/typing.py", line 649, in __getitem__
    return Union[arg, type(None)]
  File "/usr/lib/python3.5/typing.py", line 552, in __getitem__
    dict(self.__dict__), parameters, _root=True)
  File "/usr/lib/python3.5/typing.py", line 512, in __new__
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "/usr/lib/python3.5/typing.py", line 512, in <genexpr>
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "/usr/lib/python3.5/typing.py", line 1077, in __subclasscheck__
    if super().__subclasscheck__(cls):
  File "/usr/lib/python3.5/abc.py", line 225, in __subclasscheck__
    for scls in cls.__subclasses__():
TypeError: descriptor '__subclasses__' of 'type' object needs an argument
`

### Details

* OS: Ubuntu 16.04
* Python version: 3.5.2
* aiosqlite version: Latest
* Can you repro on master? -
* Can you repro in a clean virtualenv? I don't have venv

**Comment by jreese** [comment]
I can replicate on python 3.5.2, but not on 3.5.5.  Looks like an issue with `Optional[Type]`, which is rather important to the type hints.  In this case, we can probably just wrap those in string literals.
