### ISSUE TITLE
Tests failing on PyPy

### ISSUE THREAD

**Issue by Snawoot** [jreese/aiosqlite#32]
### Description

Test suite failing on PyPy:

```
(venv_pypy3) user@dt1:~/aiosqlite$ python3 --version
Python 3.5.3 (eb6e70a9658e, Apr 19 2019, 14:30:38)
[PyPy 7.1.0-alpha0 with GCC 6.3.0 20170516]
(venv_pypy3) user@dt1:~/aiosqlite$ python3 -m coverage run -m aiosqlite.tests
test_connection_await (aiosqlite.tests.smoke.SmokeTest) ... ok
test_connection_context (aiosqlite.tests.smoke.SmokeTest) ... ok
test_connection_locations (aiosqlite.tests.smoke.SmokeTest) ... ok
test_connection_properties (aiosqlite.tests.smoke.SmokeTest) ... FAIL
test_context_cursor (aiosqlite.tests.smoke.SmokeTest) ... ok
test_enable_load_extension (aiosqlite.tests.smoke.SmokeTest)
Assert that after enabling extension loading, they can be loaded ... skipped "python was not compiled with sqlite3 extension support, so we can't test it"
test_fetch_all (aiosqlite.tests.smoke.SmokeTest) ... ok
test_iterable_cursor (aiosqlite.tests.smoke.SmokeTest) ... ok
test_multiple_connections (aiosqlite.tests.smoke.SmokeTest) ... ok
test_multiple_queries (aiosqlite.tests.smoke.SmokeTest) ... ok

======================================================================
FAIL: test_connection_properties (aiosqlite.tests.smoke.SmokeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/venv_pypy3/site-packages/aiounittest/helpers.py", line 139, in wrapper
    return loop.run_until_complete(future)
  File "/opt/pypy3-deb9-yarmak/lib-python/3/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/opt/pypy3-deb9-yarmak/lib-python/3/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/opt/pypy3-deb9-yarmak/lib-python/3/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/user/aiosqlite/aiosqlite/tests/smoke.py", line 169, in test_connection_properties
    self.assertEqual(db.text_factory, str)
AssertionError: <function _unicode_text_factory at 0x00005603b32ac7a0> != <class 'str'>

----------------------------------------------------------------------
Ran 10 tests in 1.148s

FAILED (failures=1, skipped=1)
```

Not to mention `typed-ast` doesn't builds on PyPy, but it's not mandatory for test suite.

### Details

* OS: Debian 9
* Python version: Python 3.5.3 (eb6e70a9658e, Apr 19 2019, 14:30:38) [PyPy 7.1.0-alpha0 with GCC 6.3.0 20170516] on linux
* aiosqlite version: 0.10.0
* [x] Can you repro on master?
* [x] Can you repro in a clean virtualenv?

**Comment by jreese** [comment]
Looks like this is because pypy3's low-level sqlite3 implementation uses pypy's non-standard unicode system for dealing with strings.
