### ISSUE TITLE
how do I call create_function?

### ISSUE THREAD

**Issue by BrannonKing** [jreese/aiosqlite#54]
This fails with a cross-thread violation:
```
db._conn.create_function, "NEEDS_UPDATE", 5,
                 lambda id, name, original, update, activation:
                 queue.put_nowait({
                     "claimID": id, "name": name, "originalHeight": original,
                     "updateHeight": update, "activationHeight": activation
                 })
```
If I then put that into `await db._execute(...)` it fails with this error:
```
  File "/home/brannon/Workspace/lbry-sdk/venv/lib/python3.7/site-packages/aiosqlite/core.py", line 167, in _execute
    return await future
  File "/home/brannon/Workspace/lbry-sdk/venv/lib/python3.7/site-packages/aiosqlite/core.py", line 153, in run
    result = function()
TypeError: argument 1 must be str, not list
```

**Comment by BrannonKing** [comment]
With named parameters I get this error:
```
  File "/home/.../lbry-sdk/venv/lib/python3.7/site-packages/aiosqlite/core.py", line 167, in _execute
    return await future
  File "/home/.../lbry-sdk/venv/lib/python3.7/site-packages/aiosqlite/core.py", line 153, in run
    result = function()
TypeError: function missing required argument 'narg' (pos 2)
```

**Comment by sm-Fifteen** [comment]
Same issue here:

```py
import aiosqlite
def foo():
    return 'foo'

async def test_ffi():
    async with aiosqlite.connect(':memory:') as db:
        db._conn.create_function("foo", 0, foo)
        async with db.execute("SELECT foo();") as res:
            row = await res.fetchone()
            print(row)

async def test_no_ffi():
    async with aiosqlite.connect(':memory:') as db:
        async with db.execute("SELECT 'foo';") as res:
            row = await res.fetchone()
            print(row)
```

```py
>>> import asyncio
>>> asyncio.run(test_no_ffi())
('foo',)
>>> asyncio.run(test_ffi())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python\Python38\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python\Python38\lib\asyncio\base_events.py", line 608, in run_until_complete
    return future.result()
  File "<stdin>", line 3, in test_ffi
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 18820 and this is thread id 3156.
```

It's not *required* for my use-case, but FFI functions not being available is going to be a problem for some.
